FROM ubuntu:16.04

RUN apt-get update  && \
	apt-get install -y curl vim nodejs net-tools

RUN curl -sL https://deb.nodesource.com/setup_8.x | bash -

#RUN apt-get install -y nodejs

#RUN apt-get install -y net-tools

EXPOSE 3000
